name: flutter_yoco
description: A simple flutter plugin to integrate Yoco payment gateway into your flutter app.
version: 1.0.1
repository: 'https://github.com/Miso-0/flutter_yoco.git'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/flutter_yoco/assets/cancelled.png
    - packages/flutter_yoco/assets/checked.png
    - packages/flutter_yoco/assets/warning.png
    - packages/flutter_yoco/assets/yoc_logo.png

platforms:
  android:
  ios:

topics:
  - payment
  - yoco
  - paystack
  - stripe
  - paypal
