name: flutter_yoco
description: A simple flutter plugin to integrate Yoco payment gateway into your flutter app.
version: 1.0.0
homepage: "https://dev-miso.web.app"
repository: "https://github.com/Miso-0/flutter_yoco.git"

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


